In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [5]:
df = df.sample(frac=1)

In [7]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
746            1      147             94             41        0  49.3   
388            5      144             82             26      285  32.0   
479            4      132             86             31        0  28.0   
587            6      103             66              0        0  24.3   
447            0       95             80             45       92  36.5   
..           ...      ...            ...            ...      ...   ...   
79             2      112             66             22        0  25.0   
121            6      111             64             39        0  34.2   
211            0      147             85             54        0  42.8   
41             7      133             84              0        0  40.2   
440            0      189            104             25        0  34.3   

     DiabetesPedigreeFunction  Age  Outcome  
746                     0.358   27        1  
388                     0.452   58        1  
479                     0.419   63        0  
587                     0.249   29        0  
447                     0.330   26        0  
..                        ...  ...      ...  
79                      0.307   24        0  
121                     0.260   24        0  
211                     0.375   24        0  
41                      0.696   37        0  
440                     0.435   41        1  

[768 rows x 9 columns]

In [9]:
X = df.drop (['Outcome'], axis=1).values
y = df['Outcome'].values

In [10]:
X

array([[  1.   , 147.   ,  94.   , ...,  49.3  ,   0.358,  27.   ],
       [  5.   , 144.   ,  82.   , ...,  32.   ,   0.452,  58.   ],
       [  4.   , 132.   ,  86.   , ...,  28.   ,   0.419,  63.   ],
       ...,
       [  0.   , 147.   ,  85.   , ...,  42.8  ,   0.375,  24.   ],
       [  7.   , 133.   ,  84.   , ...,  40.2  ,   0.696,  37.   ],
       [  0.   , 189.   , 104.   , ...,  34.3  ,   0.435,  41.   ]])

In [11]:
y

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [13]:
knn = KNeighborsClassifier()

In [14]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [15]:
y_pred = knn.predict(X_test)

In [16]:
y_pred

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0], dtype=int64)

In [17]:
accuracy_score(y_pred, y_test)

0.65625

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
std = StandardScaler()
X_train_scaled = std.fit_transform(X_train)

In [20]:
X_test_scaled = std.transform(X_test)

In [21]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [22]:
y_pred = knn.predict(X_test_scaled)

In [23]:
accuracy_score(y_test, y_pred)

0.7552083333333334